### PR TITLE
Add a dockerfile for the bare executor that includes gcc

### PR DESCRIPTION
**Pull request by maggie-lou**
Add a dockerfile for the bare executor that includes gcc, which is needed to do bazel builds

Used in https://github.com/buildbuddy-io/buildbuddy-internal/pull/2283

### CODE REVIEW

**Comment by maggie-lou** [comment]
Current dependencies on/for this PR:
* master
  * **PR #4008** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/4008" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/4008?utm_source=stack-comment).

**Review by bduffany — COMMENTED** [review]
hm why is GCC needed? IIUC the bare executor will only execute the go test actions, which should be in Go (not C/C++)

**Comment by maggie-lou** [comment]
> hm why is GCC needed? IIUC the bare executor will only execute the go test actions for `firecracker_test`, which should be in Go (not C/C++). The bare executor won't be doing bazel builds - instead the `ci_runner` / `bazel` processes could still be run by the current `executor-workflows` pool and the remote actions will just be spawned on the bare executor.

I modified things so that the `bazel` process is run in the executor-workflows pool. I'm still getting this gcc error though

external/go_sdk_linux/pkg/tool/linux_amd64/link: running /usr/bin/gcc failed: fork/exec /usr/bin/gcc: no such file or directory
link: error running subcommand external/go_sdk_linux/pkg/tool/linux_amd64/link: exit status 2
Target //enterprise/server/remote_execution/containers/firecracker:firecracker_test failed to build

https://app.buildbuddy.dev/invocation/0da196af-97ff-4948-8d60-1ba159081db5

**Comment by maggie-lou** [comment]
> > > hm why is GCC needed? IIUC the bare executor will only execute the go test actions for `firecracker_test`, which should be in Go (not C/C++). The bare executor won't be doing bazel builds - instead the `ci_runner` / `bazel` processes could still be run by the current `executor-workflows` pool and the remote actions will just be spawned on the bare executor.
> > 
> > 
> > I modified things so that the `bazel` process is run in the executor-workflows pool. I'm still getting this gcc error though
> > external/go_sdk_linux/pkg/tool/linux_amd64/link: running /usr/bin/gcc failed: fork/exec /usr/bin/gcc: no such file or directory link: error running subcommand external/go_sdk_linux/pkg/tool/linux_amd64/link: exit status 2 Target //enterprise/server/remote_execution/containers/firecracker:firecracker_test failed to build
> > https://app.buildbuddy.dev/invocation/0da196af-97ff-4948-8d60-1ba159081db5
> 
> Ah, I guess this is because the `exec_properties` on `firecracker_test` are being applied to all of the underlying actions - including the actions that compile and link the test, as well as the action that actually executes the test.
> 
> To work around this, you can use `--modify_execution_info` to force the link action to execute locally, just for the `Baremetal tests` workflow.
> 
> Based on `bazel aquery //enterprise/server/remote_execution/containers/firecracker:firecracker_test --output=summary` it seems like the action mnemonic for that Go link action might be `GoLink`, so maybe `--modify_execution_info=^GoLink$=+local` will work?

Thanks Brandon for all your help 🙏 🙏 Finally got all the tests to pass and without needing a new image

**Pull request closed without merging**
