### PR TITLE
app/executors: improve OS/Arch UI

### PR DESCRIPTION
**Pull request by sluongng**
When helping a customer troubleshoot their executor pools,
it was not clear visually which pool was which between multiple
"Default" pools with different OS/Arch combination.

Move the OS/Arch information to their dedicated lines to better display
different attributes of a pool.

**Related issues**: N/A

### CODE REVIEW

**Comment by sluongng** [comment]
image

Quick preview of how it would look like with this PR

**Comment by siggisim** [comment]
This feels like it takes up a lot of vertical space, maybe we could add them as little chips after the pool name?

**Comment by bduffany** [comment]
Pushed a commit to fix some layout/alignment issues - 
image

(Feel free to remove the commit, just figured it was easier than making a bunch of PR comments)

**Comment by sluongng** [comment]
That looks so much better wow. Nicely done!

**Review by bduffany — APPROVED** [review]

**Pull request merged**
