### PR TITLE
Upgrade `go` version to 1.19

### PR DESCRIPTION
**Pull request by tempoz**
Bumps the versions for `gazelle`, `rules_go`, and `bazel`.

---

**Version bump**: Patch

### CODE REVIEW

**Comment by tempoz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2995** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2995" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2995?utm_source=stack-comment).

**Review by bduffany — COMMENTED** [review]
Tyler tried to do this but hit an issue that the CI runner image has an outdated version of GCC: https://buildbuddy-corp.slack.com/archives/C01D5GHRJ59/p1669055224356229

We could try to install GCC in the CI runner image but it might break some people.

The path forward might be to upgrade the CI runner image to 20.04, but it's a bit tricky. More context: https://github.com/buildbuddy-io/buildbuddy-internal/issues/1538

**Comment by tylerwilliams** [comment]
I'm fine disabling race detection in the .bazelrc "ci" config until we can upgrade the runner image -- that should make CI happy here. I don't want to block the go version upgrade on the CI image upgrade.

@bduffany hoping you can look at upgrading the CI image / figuring that story out

**Comment by bduffany** [comment]
> @bduffany hoping you can look at upgrading the CI image / figuring that story out

I filed an issue here with some basic details https://github.com/buildbuddy-io/buildbuddy-internal/issues/1830

Will look into addressing that next.

**Comment by bduffany** [comment]
looks like you're hitting the issue where the race detector doesn't build due to the outdated CI runner image version:

commenting out this line in `.bazelrc` should fix:
 
```
# TODO(https://github.com/buildbuddy-io/buildbuddy-internal/issues/1830): Re-enable
# build:workflows --@io_bazel_rules_go//go/config:race
```

**Pull request merged**
