### PR TITLE
Delete timing profile from cache after copying to blobstore

### PR DESCRIPTION
**Pull request by tempoz**
Don't continue to persist the timing profile in the cache after it has been stored in blobstore,
as it would be redundant and use up cache that could be devoted to something else.

---

**Version bump**: Minor

### CODE REVIEW

**Comment by tempoz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3717** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3717" target="_blank">Graphite</a> 
    * **PR #3718** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3718" target="_blank">Graphite</a> 
      * **PR #3719** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3719" target="_blank">Graphite</a> 
        * **PR #3720** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3720" target="_blank">Graphite</a> 
          * **PR #3721** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3721" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3721?utm_source=stack-comment).

**Comment by tempoz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3717** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3717" target="_blank">Graphite</a> 
    * **PR #3718** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3718" target="_blank">Graphite</a> 
      * **PR #3719** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3719" target="_blank">Graphite</a> 
        * **PR #3720** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3720" target="_blank">Graphite</a> 
          * **PR #3721** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3721" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/3721?utm_source=stack-comment).

**Comment by siggisim** [comment]
> I think we should hold off on this for now just to avoid breaking the contract that when something is uploaded to cache, it'll be persisted there for a reasonable amount of time.
> 
> e.g. it's unclear whether we have any users that are using the public invocation API to analyze timing profiles, and are relying on the profiles to be in the cache.
> 
> (We can always revisit this in the future if we can do some analysis and find that the timing profiles are causing a significant amount of cache churn.)

They can grab their timing profiles locally from their CI runners - if this becomes an issue (which I don't think it will), we can always add an endpoint for them to fetch it that respects the fallback.

**Review by vadimberezniker — CHANGES_REQUESTED** [review]
I think it's okay to leave these artifacts in the cache. Best case we can serve them directly from cache instead of falling back to blobstore. And if nobody is accessing them, they will be naturally evicted from the cache.

**Pull request closed without merging**
