### PR TITLE
event_parser: set username on Gitlab CI

### PR DESCRIPTION
**Pull request by sluongng**
For gitlab customers, it would be ideal to use GITLAB_USER_NAME instead
of USER to identify the user.

### CODE REVIEW

**Comment by sluongng** [comment]
Context for this https://buildbuddy-corp.slack.com/archives/C065U1KU8KE/p1706542779444159

**Review by siggisim — CHANGES_REQUESTED** [review]
If we did this, we would probably want to do it for Github, BuildKite, etc as well.

You'd also need to update the docs and bunch more references. See this PR as an example: https://github.com/buildbuddy-io/buildbuddy/pull/5988/files

**Comment by siggisim** [comment]
Can you add these to the list in the "Environment variable redacting" section in the docs too?

**Review by siggisim — CHANGES_REQUESTED** [review]
Here: https://github.com/buildbuddy-io/buildbuddy/blob/ae192fa688c26d3a0e6c226995d5888ea458d6d8/docs/guide-metadata.md?plain=1#L241

**Comment by sluongng** [comment]
@siggisim I added them to the redact doc.

I think these variables are exposed to the frontend to display in the "Invocation details" card. Do you want to include that in this PR as well? 🤔

**Review by siggisim — APPROVED** [review]
Cool either way on that one.

Lgtm!

**Pull request merged**
