### PR TITLE
Add a very simple workflow that the probers can use to test workflow health

### PR DESCRIPTION
**Pull request by maggie-lou**
**Related issues**: Used in this script: https://github.com/buildbuddy-io/buildbuddy/pull/6628

### CODE REVIEW

**Review by bduffany — COMMENTED** [review]
Could you put this in a separate private repo like `buildbuddy-io/buildbuddy-workflow-probers` and register that repo to the probers org(s) in dev/prod? Just would like to avoid adding noise to the GitHub statuses published to commits in the OSS repo, as well as our build history in the BB org.

**Comment by maggie-lou** [comment]
@bduffany Re-opening because we can only link a github app to 1 BB org. I considered using remote bazel in the prober instead, but we'd have to clone a git repo, which feels too heavy weight for a prober.

**Comment by bduffany** [comment]
I just added `buildbuddy-io/probers` to the repos allowed by the app installation and linked it to the BB org, so you could try testing that out?

**Comment by maggie-lou** [comment]
> I just added `buildbuddy-io/probers` to the repos allowed by the app installation and linked it to the BB org, so you could try testing that out?

Oh duh you're right. That works

**Pull request closed without merging**
