### PR TITLE
Dial* -> Dial*WithoutPooling in a few places

### PR DESCRIPTION
**Pull request by jdhollen**
This seems like the right choice for these lines regardless, but we could also try to mess with when we even use the otel interceptor?

**Related issues**: N/A

### CODE REVIEW

**Review by tylerwilliams — APPROVED** [review]
LGTM but maybe let @vadimberezniker have a look too :)

**Comment by vadimberezniker** [comment]
I think the real problem is that grpc_client.DialInternal is being called for every streaming request, not the fact that we create a pool of connections. For build_event_publisher and telemetry_client I don't see any harm in creating a pool of connections. I'd prefer to keep the package simple. I was hopeful we could eventually remove the WithoutPooling variants of the functions.

**Comment by jdhollen** [comment]
> I think the real problem is that grpc_client.DialInternal is being called for every streaming request, not the fact that we create a pool of connections. For build_event_publisher and telemetry_client I don't see any harm in creating a pool of connections. I'd prefer to keep the package simple. I was hopeful we could eventually remove the WithoutPooling variants of the functions.

Yeah, I mean, if we kill all ad-hoc `Dial` calls, then it doesn't matter.  I took a stab at that in #5396, and this was just something quick I got out because it is at least a sure thing and would slow down the bleed from this issue by an order of magnitude (in case the other fix doesn't work).

This only matters if we want a backup for the other change.

**Comment by jdhollen** [comment]
the extra dial calls here are theoretically also histogram leaks, just not at the scale of the bytestream code--we can just use the reuse logic for them, too.

**Pull request closed without merging**
