### PR TITLE
Run firecracker workflows with `init-dockerd: true`

### PR DESCRIPTION
**Pull request by bduffany**
**Related issues**: N/A

### CODE REVIEW

**Review by siggisim — APPROVED** [review]
Do we need to add docker here:
- https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/dockerfiles/ci_runner_image/Dockerfile

and 
- https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/dockerfiles/rbe-ubuntu20-04-workflows/Dockerfile

**Comment by bduffany** [comment]
> Do we need to add docker here:
> 
> * https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/dockerfiles/ci_runner_image/Dockerfile
> 
> and
> 
> * https://github.com/buildbuddy-io/buildbuddy/blob/master/enterprise/dockerfiles/rbe-ubuntu20-04-workflows/Dockerfile

No, it's available in the base images.

**Comment by bduffany** [comment]
Actually, it looks like we have it installed in the 16.04 image (RBE default) and 20.04 image but not the 18.04 image, and I forgot that the default workflows image is based on 18.04.

```
# 20.04 (opt-in)
$ podman run --rm -it gcr.io/flame-public/rbe-ubuntu20-04-workflows@sha256:eb81189af1cec44b5348751f75ec7aea516d0de675b8461235f4cc4e553a34b5 which dockerd
/usr/bin/dockerd

# 18.04 (default)
$ podman run --rm -it gcr.io/flame-public/buildbuddy-ci-runner@sha256:ba33bd1b3acdfe980b958baf7d05c2041c9d4183d15fdf665dd236289d777709 which dockerd
<nothing>
```

**Comment by bduffany** [comment]
> Will add it to the 18.04 image.

Done:

```
$ podman run --rm -it gcr.io/flame-public/buildbuddy-ci-runner@sha256:6381c06bee2910e66903784b4a90cb9ff08823686da46cf6874902c9f8428e69 which dockerd
/usr/bin/dockerd
```

**Pull request merged**
