### PR TITLE
task-routing: Add executor instance ID fields to protos and ExecutionNode table

### PR DESCRIPTION
**Pull request by bduffany**
Adding instance ID field to the following places:
* `RegisterNodeRequest` so that the scheduler can get the executor ID as part of the registration. Also added to `ExecutionNode` since the `scheduler_client` uses this internally to represent the current executor.
* `EnqueueTaskReservationRequest` so that the scheduler can enqueue task reservations on a specific executor.
* `ExecutedActionMetadata` so that the execution server can inform the task router as to which executor completed the action.
* `ExecutionNodes` table so that we know the IDs when passing the allowed list of execution nodes to the router.

---

**Version bump**: Patch

### CODE REVIEW

**Review by vadimberezniker — APPROVED** [review]

**Review by tylerwilliams — APPROVED** [review]
LGTM

**Comment by bduffany** [comment]
Instead of executor address, now using executor instance ID per our discussion -- PTAL

**Review by vadimberezniker — APPROVED** [review]
Would have been better to send formatting changes as a separate PR.

**Comment by bduffany** [comment]
> Would have been better to send formatting changes as a separate PR.

My mistake, I updated VSCode to auto-format with `--style=Google` and this crept in unnoticed.

**Review by tylerwilliams — CHANGES_REQUESTED** [review]
Can we call this ExecutorID / executor_id everywhere?

**Comment by bduffany** [comment]
> Can we call this ExecutorID / executor_id everywhere?

Done

**Review by tylerwilliams — APPROVED** [review]
LGTM

**Pull request merged**
