### PR TITLE
Timelines for action page

### PR DESCRIPTION
**Pull request by pariparajuli**
Separated timelines for execution metadata

### CODE REVIEW

**Comment by pariparajuli** [comment]
Screen Shot 2021-07-30 at 3 21 18 PM

**Comment by bduffany** [comment]
Much improved!

Mind double-checking that the timing numbers on the right are readable (high enough contrast) if they are displayed on top of the colors? You can easily check by setting the flex weight of the gray bar to 0.

**Comment by pariparajuli** [comment]
the way i have the divs set up, the text can't sit on top of colors, if there is a bar that's too long, the text ends up overflowing to the side, i was thinking of putting the text within the bars on the right side above the bar itself

**Comment by bduffany** [comment]
> i was thinking of putting the text within the bars on the right side above the bar itself

That sounds like a good option

**Comment by pariparajuli** [comment]
Screen Shot 2021-08-02 at 2 53 17 PM

**Review by bduffany — APPROVED** [review]
So much nicer!

**Pull request merged**
