### PR TITLE
change default container image to 20.04

### PR DESCRIPTION
**Pull request by sluongng**
This is a follow up from
https://github.com/buildbuddy-io/buildbuddy-toolchain/pull/25

### CODE REVIEW

**Review by bduffany — CHANGES_REQUESTED** [review]
I think this will break people who aren't setting a container-image explicitly in their actions, no?

**Comment by bduffany** [comment]
I think it'd be good to add some logging first to see if there are any customers who aren't explicitly setting the container image, and proactively warn them about this upcoming change

**Comment by siggisim** [comment]
Yeah, I think we should avoid breaking changes like these. We should recommend folks upgrade their toolchain version if they'd like a newer base image, and should generally recommend against using the empty value here.

**Comment by sluongng** [comment]
Alright, let's close this for now and think about what to do with empty `container-image` `exec_properties` value 🤔

**Pull request closed without merging**
