### PR TITLE
Don't ignore workspace creation errors

### PR DESCRIPTION
**Pull request by bduffany**
---

**Version bump**: Patch

### CODE REVIEW

**Review by tylerwilliams — APPROVED** [review]
LGTM

(is there a linter we can enable to catch these?)

**Review by vadimberezniker — APPROVED** [review]
Yikes.

**Comment by bduffany** [comment]
This was highlighted in my editor:

```
this value of err is never used (SA4006) go-staticcheck
```

but I am not sure if this triggers a build failure. @tempoz any ideas?

**Comment by tempoz** [comment]
@bduffany the compiler is permissive about re-assigning values as long as they're "used" in the block anywhere, regardless of if that particular assignment is ever used/checked.

**Pull request merged**
