### PR TITLE
Add support for specifying an "session affinity key" in the Run API.

### PR DESCRIPTION
**Pull request by vadimberezniker**
This allows clients to specify preference as to which Bazel instance
their requests get routed.

---

**Version bump**: None

### CODE REVIEW

**Review by tylerwilliams — APPROVED** [review]
LGTM

Would be nice to add a test for this?

**Review by bduffany — COMMENTED** [review]
WDYT about implementing this as a suffix on the remote instance name?

**Comment by vadimberezniker** [comment]
> LGTM
> 
> Would be nice to add a test for this?

added tests

**Comment by vadimberezniker** [comment]
> WDYT about implementing this as a suffix on the remote instance name?

I think eventually we'll want to be able to propagate the instance name down the hosted bazel process. 
When that's implemented, relying on instance name for routing would unnecessarily cause cache misses.

**Pull request merged**
