### PR TITLE
Disable flaky cache requests card assertions

### PR DESCRIPTION
**Pull request by bduffany**
**Related issues**: https://github.com/buildbuddy-io/buildbuddy-internal/issues/3719

### CODE REVIEW

**Comment by maggie-lou** [comment]
Hot take - I'd kind of prefer leaving the flaky test so there's some incentive to fix it

**Comment by tylerwilliams** [comment]
> Hot take - I'd kind of prefer leaving the flaky test so there's some incentive to fix it

I mostly agree (and think we should fix this!), but when it blocks the releases from succeeding and someone has to notice and go mash the retry button a bunch (waiting each time to see if it's successful), it feels like a net negative.

**Review by tylerwilliams — APPROVED** [review]

**Comment by maggie-lou** [comment]
I kind of feel like it's the on-call person's job to fix the test in that case? I'm on call next week so I'll put my money where my mouth is and fix it when it inevitably burns me :P

**Comment by tylerwilliams** [comment]
lol I feel like this is a be careful what you wish for situation -- but I'm happy to close this for now and we can chat offline about prioritizing the flakes that need fixing!

**Pull request closed without merging**
