### PR TITLE
Add run as root option for docker to yaml config

### PR DESCRIPTION
**Pull request by tempoz**
This change is necessary but not sufficient to add the "run as root" functionality for docker. It makes possible buildbuddy-io/buildbuddy-internal/pull/333

---

**Version bump**: Minor

### CODE REVIEW

**Review by tylerwilliams — APPROVED** [review]
LGTM

**Review by tylerwilliams — CHANGES_REQUESTED** [review]
On second thought -- do we need to change the config file at all?

If we're already running stuff as root -- the parameter change seems like enough to allow us to set that flag.

**Comment by tempoz** [comment]
So, the reason I made this change is that this structure is the one that gets passed around containing the docker config for running a docker command. SPecifically, we need to propagate the setting from [here](https://github.com/buildbuddy-io/buildbuddy-internal/blob/master/enterprise/server/remote_execution/executor/executor.go#L241) to [here](https://github.com/buildbuddy-io/buildbuddy-internal/blob/master/enterprise/server/remote_execution/containers/docker/docker.go#L40), unless I misunderstand. It seemed like the simplest way to do that was to just add an additional setting to the executor config (which can then be conditionally set in that first function), but it's possible that this is breaking a pattern I am unaware of (for instance, if the config is not supposed to be mutated in code). It's also possible that it should be marked for internal use only?

**Comment by tylerwilliams** [comment]
Chatted over VC (my fingers thank you) -- but we should be able to do this all over on the other cL!

**Comment by tempoz** [comment]
Closing this, it is no longer necessary.

**Pull request closed without merging**
