### PR TITLE
[WIP] Migrate to rules_js

### PR DESCRIPTION
**Pull request by bduffany**
Rebases @thesayyn's PR https://github.com/buildbuddy-io/buildbuddy/pull/2143

Tested:
- [x] Can build and run OSS app
- [x] Can build and run enterprise app
- [x] Can build and run server image from internal repo
  - [x] Depends on https://github.com/aspect-build/rules_swc/pull/128
  - [x] Depends on https://github.com/aspect-build/rules_esbuild/pull/108
- [ ] Make sure disk usage is acceptable - the new rules do a lot of copying, and we might need to increase the disk space available to workflows to accommodate this, or see if there is a way to use less disk space, e.g. hardlinking 
- [ ] Should not break website deploy rules 
- [ ] Test dev push to make sure there is no app bundle SHA mismatch
- [x] RBE Performance: `bazel build //enterprise/app:app_bundle --config=remote-dev`: LGTM; improved by about 2s (15s -> 13s, N=100)
  - Update: This should now be even faster than the results shown above, since rules_swc was updated to use a rust-based CLI (swcx) rather than using a nodejs wrapper around swc. 
- [x] RBE Performance: `bazel test //app/... //enterprise/app/... --config=remote-dev --nocache_test_results`: LGTM; improved by about 0.6s (7.5s -> 6.9s, N=100)

---

**Version bump**: Patch

### CODE REVIEW

**Comment by bduffany** [comment]
Revisiting now that we're on Bazel 6.0

**Comment by bduffany** [comment]
FYI I am just waiting on https://github.com/aspect-build/rules_swc/pull/128/files and https://github.com/aspect-build/rules_esbuild/pull/108 to get merged upstream.

**Comment by sluongng** [comment]
It seems like for this to work, we gonna need to migrate `//website` from yarn to `pnpm`, then use the `@pnpm//:pnpm` binary in replacement for `@yarn//:yarn` binary 🤔 

I found this which could be helpful https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04

**Comment by sluongng** [comment]
Example on how to migrate docusaurus targets https://github.com/formatjs/formatjs/blob/2d7bd516d7e6fc85d3e208bac390d81396d43d17/website/BUILD

**Comment by bduffany** [comment]
Will re-open once I have the bandwidth to pick up work on this again.

**Pull request closed without merging**
