### PR TITLE
workflows: Add GetRepos RPC and impl stub

### PR DESCRIPTION
**Pull request by bduffany**
GetRepos will be used to render a list of repos linked to the authenticated user's GitHub account (we'll return an error if the GitHub account is not linked -- the client is responsible for checking group.isGitHubLinked before making this RPC)

---

**Version bump**: Patch

### CODE REVIEW

**Review by siggisim — APPROVED** [review]
This looks good to me, but let's make sure @tylerwilliams  doesn't hate it.

My only concern is whether or not the client will know which GitProvider to pass up in the requests.

**Comment by siggisim** [comment]
Yuck, automerge lol - hope you didn't have any concerns Tyler!

**Comment by tylerwilliams** [comment]
LGTM!

**Comment by bduffany** [comment]
@siggisim for now the plan is to check `isGitHubAccountLinked` and if so then always make the request with `provider = GITHUB`.

**Pull request merged**
