### PR TITLE
write out test target cached-ness to db

### PR DESCRIPTION
**Pull request by jdhollen**
**Related issues**: N/A

### CODE REVIEW

**Comment by jdhollen** [comment]
I'm not sure what the "preferred" way to submit this is--with the defaults, i think i can split it up and just put the schema change in first?  happy to split that up if that's what we like, since it'll make cherrypicking the schema change a little easier.

**Review by tylerwilliams — APPROVED** [review]
This LGTM, I'll let lulu comment on any schema upgrade or other concerns

**Comment by luluz66** [comment]
> I'm not sure what the "preferred" way to submit this is--with the defaults, i think i can split it up and just put the schema change in first? happy to split that up if that's what we like, since it'll make cherrypicking the schema change a little easier.

Yeah. change lgtm. prefer schema change to be a seperate pr just in case.

**Comment by jdhollen** [comment]
> Yeah. change lgtm. prefer schema change to be a seperate pr just in case.

Sure sure, https://github.com/buildbuddy-io/buildbuddy/pull/6890, will plop this one in after.

**Review by luluz66 — APPROVED** [review]

**Pull request merged**
