### PR TITLE
Retrieve ACKs from build event proxy

### PR DESCRIPTION
**Pull request by glukasiknuro**
Found out that when using proxy some streams were not complete. It's
because the build event server to which traffic was proxied was sending
ACKs messages along the way, but buildbuddy was not retrieving it,
so those were accumulated till some buffers were filled up.

---

**Version bump**: Patch

### CODE REVIEW

**Review by tylerwilliams — APPROVED** [review]
LGTM

Hey @glukasiknuro, this looks great, thanks for sending a PR to fix!

**Comment by tylerwilliams** [comment]
@glukasiknuro Looks like the checkstyle presubmit is failing -- would you mind running go fmt on this and then we can merge it? LMK if this is an issue.

**Comment by glukasiknuro** [comment]
> @glukasiknuro Looks like the checkstyle presubmit is failing -- would you mind running go fmt on this and then we can merge it? LMK if this is an issue.

Done. I guess it needs "Approve and run" to re-run checkstyle.

**Comment by tylerwilliams** [comment]
You have good timing; this CL went out in our release (https://github.com/buildbuddy-io/buildbuddy/releases/tag/v2.7.3) today :)

Thanks again for the PR!

**Pull request merged**
