### PR TITLE
track uploaded snapshot bytes.

### PR DESCRIPTION
**Pull request by jdhollen**
**Related issues**: N/A

### CODE REVIEW

**Comment by jdhollen** [comment]
this is my dumb idea for how to do this, please tell me if you think i should do it a different way.

**Review by tylerwilliams — APPROVED** [review]

**Comment by maggie-lou** [comment]
How does this differ from this metric? https://github.com/buildbuddy-io/buildbuddy/blob/3ba0238272a89f4b928f8629bdc232b1de0810f6/server/metrics/metrics.go#L1281

Dashboard: https://metrics.buildbuddy.io/d/KI6NxDWSk/workflow-snapshotting?orgId=1&refresh=1m&editPanel=14

**Comment by jdhollen** [comment]
> How does this differ from this metric?
> 
> https://github.com/buildbuddy-io/buildbuddy/blob/3ba0238272a89f4b928f8629bdc232b1de0810f6/server/metrics/metrics.go#L1281
> 
> Dashboard: https://metrics.buildbuddy.io/d/KI6NxDWSk/workflow-snapshotting?orgId=1&refresh=1m&editPanel=14

We also call `snaputil.Cache` for everything in `range enumerateFiles(opts)` -- is this actually empty for some reason? i was worried that there might be a meaningful discrepancy here for whatever reason (if i'm not misunderstanding)

**Comment by maggie-lou** [comment]
> We also call snaputil.Cache for everything in range enumerateFiles(opts) -- is this actually empty for some reason? i was worried that there might be a meaningful discrepancy here for whatever reason (if i'm not misunderstanding)

Hmmm I guess it could be interesting to see if those are unexpectedly large. Many of the files in `range enumerateFiles(opts)` are static though - it's contains things like the kernel and initrd images

At the very least, should we consolidate the two metrics?

**Comment by jdhollen** [comment]
yup exactly--this should be static but it'd be good to see if there's unexpectedly a bunch of data flooding into the cache from somewhere.

and sure, i didn't think of that, we could just make some kind of "datatype" attr or something on the new metric and ditch the cow one?  does that sound good?

**Comment by maggie-lou** [comment]
Sure sounds good. The old metric has a `fileName` label that we could use. The only slight preference for using the old metric is that we'll have more data if we want to query metric history, but prometheus doesn't keep data for that long anyway. If you switch to the new metric, reminder to update the grafana dashboard that reads from it

**Pull request merged**
