### PR TITLE
Prevent disk cache race condition when cleaning up temp files

### PR DESCRIPTION
**Pull request by maggie-lou**
The disk cache tests have been really flaky for me due to a race condition where temp files are being deleted by the initialization function at the same time as when we're trying to [set data in unit tests](https://github.com/buildbuddy-io/buildbuddy/blob/master/server/util/disk/disk.go#L81)

### CODE REVIEW

**Comment by maggie-lou** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2730** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2730" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/2730?utm_source=stack-comment).

**Comment by vadimberezniker** [comment]
We should add a check that only deletes these stale files if they're older than a certain amount (say 15 minutes). 
I think the issue you are running into in tests can also happen under normal operation.

**Comment by maggie-lou** [comment]
> We should add a check that only deletes these stale files if they're older than a certain amount (say 15 minutes). I think the issue you are running into in tests can also happen under normal operation.

Done

**Review by vadimberezniker — APPROVED** [review]
Thanks for finding this!

**Pull request merged**
