### PR TITLE
Seed random number generator in prober so that we don't generate the same inputs every time.

### PR DESCRIPTION
**Pull request by vadimberezniker**
---

**Version bump**: None

### CODE REVIEW

**Comment by tylerwilliams** [comment]
Could you use something from /util/random instead? I think that already seeds.

**Comment by vadimberezniker** [comment]
> Could you use something from /util/random instead? I think that already seeds.

I need to call `read.Rand` to fill a buffer. I could add another function to util/random to do that but I'm not sure I see the utility.

**Comment by tylerwilliams** [comment]
yeah ok, I agree since this is in tools/

**Review by tylerwilliams — APPROVED** [review]
LGTM

**Pull request merged**
