### PR TITLE
Use flags for ssl

### PR DESCRIPTION
**Pull request by tempoz**
Restack of buildbuddy-io/buildbuddy/pull/1853

---

**Version bump**: Minor

### CODE REVIEW

**Comment by tempoz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1864** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1864" target="_blank">Graphite</a> 
    * **PR #1780** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1780" target="_blank">Graphite</a> 
      * **PR #1865** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1865" target="_blank">Graphite</a> 
        * **PR #1866** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1866" target="_blank">Graphite</a> 
          * **PR #1867** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1867" target="_blank">Graphite</a> 
            * **PR #1868** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1868" target="_blank">Graphite</a> 
              * **PR #1869** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1869" target="_blank">Graphite</a> 
                * **PR #1870** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870" target="_blank">Graphite</a>  (this PR)
                  * **PR #1778** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1778" target="_blank">Graphite</a> 
                    * **PR #1833** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1833" target="_blank">Graphite</a> 
                      * **PR #1836** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1836" target="_blank">Graphite</a> 
                        * **PR #1837** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1837" target="_blank">Graphite</a> 
                          * **PR #1838** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1838" target="_blank">Graphite</a> 
                            * **PR #1839** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1839" target="_blank">Graphite</a> 
                              * **PR #1854** <a href="https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1854" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).

**Review by luluz66 — APPROVED** [review]

**Comment by tempoz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).


Job Reference: tNi5q82iqro6xKMPIA1x

**Comment by tempoz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).


Job Reference: Kb6NfQVs9YSZkiDsKgfx

**Comment by tempoz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).


Job Reference: UWH9zAeATn6HjbQfFiuS

**Comment by tempoz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).


Job Reference: LYGXjCZ9jzXE0ra5XapW

**Comment by tempoz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).


Job Reference: bO0bzB7R9g7bK8rQ9uPT

**Comment by tempoz** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/buildbuddy-io/buildbuddy/1870?utm_source=stack-comment).


Job Reference: x9vSQMZuwVwdzOiJU1Ph

**Pull request merged**
