### PR TITLE
Make `gopls` and `go mod tidy` both happy

### PR DESCRIPTION
**Pull request by tempoz**
- Fix capture of loop variable in goroutine
- Simplify range expressions
- Simplify composite literals
- Use `go embed` directive instead of `go_embed_data` build rule
- Likely contentious change to bundle packaging

---

**Version bump**: Patch

### CODE REVIEW

**Comment by tempoz** [comment]
This PR is stacked on top of https://github.com/buildbuddy-io/buildbuddy/pull/396 , so probably better to get that one in first. Basically after working on that, I noticed how close we were to not having any gopls errors in the codebase, and I didn't have anything to do last night after work, sooooo

Through no fault of my own, these changes incidentally made go mod tidy work (specifically the bundle commit, which I kind of expect people to strongly dislike, but I thought I'd see what people thought).

**Comment by tempoz** [comment]
Also, fun fact, `go embed` directives, at least when building with `bazel`, do not recognize any of your listed `embedsrcs` if you are building a `go_test`. To my knowledge, this is nowhere on the internet and just a completely undocumented bug. So that was a fun hour and a half. But if you're like "why did she make that piddly little library in the three `test_data` directories," it was so that I could import a `go_library` that had the embedded sources into the `go_test` :P

**Review by vadimberezniker — APPROVED** [review]
LGTM

**Review by tylerwilliams — APPROVED** [review]
LGTM

Can you make sure to test the embedded stuff before committing? Just bazel build OS / enterprise server and then run it with --static_dir="" and --app_directory="" to verify that it serves from the embedded sources correctly.

**Comment by tempoz** [comment]
Absolutely; testing it now.

**Pull request merged**
